task: PRS
gpus: [0]
exp_name: 'exp'

train_dataset_module: lib.datasets.prs.pre_model
test_dataset_module: lib.datasets.prs.pre_model
network_module: lib.networks.prs.network
loss_module: lib.train.losses.PRS_Net
evaluator_module: lib.evaluators.PRS_Net
visualizer_module: lib.visualizers.prs

task_arg:
    gridBound: 0.5
    gridSize: 32
    num_plane: 3
    num_quat: 3
    initialize: True
    reg_weight: 25

network:
    input_ch: 1
    output_ch: 4
    kernel_size: 3
    conv_layer: 5

train_dataset:
    data_root: './data/processed_shapenet'
    split: 'train'
    view: 0
    input_ratio: 1.

test_dataset:
    data_root: './data/processed_shapenet'
    view: 0
    split: 'test'
    input_ratio: 0.5

train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 2000 # 100 * 500
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 20
    num_workers: 4

test:
    batch_size: 1

ep_iter: 500
eval_ep: 10       # 50 iterations
save_latest_ep: 20 # 10000 iterations
log_interval: 100
